first try dz4
ShorB/DZ3 pull request #2
Opened 2022-09-03 17:18 UTC by ShorB

2022-09-04 18:03 UTC, ShorB commented
Когда вы будете пытаться найти в поиске какую-нибудь монету, то она будет содержать урезанную информацию, потому что в ответе на запрос на поиск монет просто нет этих полей, которые есть в запросе на список всех монет. В макете нарисована карточка монеты(во время серча) такая же объемная по информации, но мне кажется, что это невозможно. Мне выводить менее объемные по информации карточки для серча или я в чем-то ошибся?

2022-09-04 20:26 UTC, nikolya98 requested changes

2022-09-04 20:26 UTC, nikolya98 commented on package.json
> +  "name": "dz4",
тут название проекта

2022-09-04 20:26 UTC, nikolya98 commented on package.json
>      "eslint": "^8.22.0",
вынести dev зависимости: линтеры, типы и т.п., всё чтоиспользуется только в процессе разработы - в devDependencies

2022-09-04 20:26 UTC, nikolya98 commented on package.json
>      "node-sass": "^7.0.1",
убрать неиспользуемые пакеты

2022-09-04 20:26 UTC, nikolya98 commented on src/App.tsx
> +  const currencyApiStore = useLocalStore(() => new CurrencyApiStore());
!!! локальные сторы лучше создавать на страницах, на которых они непосредственно нужны... если их нужно создать сразу и они нужны во многих местах, то можно хранить их в глобальном сторе как подсторы и в них же можно прокинуть ссылку на глобальный стор (this) - если понадобится боращаться из одного подстора к другому.. но это уже оверхед, такое только в более сложных проектах, тут 1 вариант... Отрефакторить

2022-09-04 20:26 UTC, nikolya98 commented on src/App.tsx
> +              setValue={(value: string) => globalStore.setValue(value)}
!!! прочитать что такое props drilling... Отрефакторить
Это связано с предыдущим пунктом: когда вынесешь локальные сторы в нужные компоненты, тогда и пропсы не надо будет передовать

2022-09-04 20:26 UTC, nikolya98 commented on src/App.tsx
> +  }, [isInputSearchOpenStore]);
!!! Отрефакторить... Вынести туда, где-это будет юзаться
В корневом компоненте в итоге только инициализация глобального стора, провайдеры, роутинг... не более!
Если есть глобальные данные, которые надо с бека получить, то можно... Но в твоём проекте такого нет... Всё можно делать в определённых местах, не в корневом компоненте

2022-09-04 20:26 UTC, nikolya98 commented on src/App.tsx
> +              currency={currenctCurrencyStore.curCurrency.toLowerCase()}
!!! Отрефакторить

2022-09-04 20:26 UTC, nikolya98 commented on src/App.tsx
> +export default observer(App);
после рефакторинга, возможно, уже будет не нужен observer

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
> +import CoinCardApiStore from "../../store/local/CoinCardApiStore/CoinCardApiStore";
алиас

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
> +  console.log(location)//eslint-disable-line
не забывай удалять такие штуки

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
> +  return coinCardApiStore.coin ? (
&&

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
>            ></div>
!!! почитать за семантику... Там где можно использовать подходящие теги... тут img подошёл бы

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
>        </div>
!!! Нижележащий блок с временными интервалом выглядит ужасно... Отрефакторить! Во-первых, можно вынести в конфиг массив [24h, 1w, 1m, ...], и потом использовать map... DRY... Во-вторых семантика, это же кнопки должны быть

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
>          <div className={styles.coin__price__container}>
!!! стили так не пишутся... почитать за БЭМ... блок__элемент_модификатор... почитай доку, посмотри на ютубе разметку по БЭМ и семантическую разметку... Советую искать материалы от html academy

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
> +            {coinCardApiStore.coin.curPrice}
посмотреть про деструктуризацию в js, в целом стараться юзать фишки современного js, когда это даёт профит...

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
>              </div>
стараться писать меньше кода, когда это возможно... тут например можно так:

d i v className={styles[`coin__price-change_${priceChange >= 0 ? 'gainer' : 'loser'}`]}>
  {`${priceChange >= 0 ? '+' : ''}${priceChange}%`}
d i v>
!!! Пересмотреть код всего проекта и посмотреть места, где можно отрефакторить, и отрефакторить

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
>              </div>
PS.. теги умышленно написал криво, чтобы гитхаб их не интерпретировал

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCardHeader/CoinCardHeader.tsx
>    let flatChangeClassNames = "coin__card__change_flat_loser";
!!! БЭМ - исправить во всём проекте 
Есть нужда создавать переменные под название класса? template string's не поможет?
!!! Посмотреть за template strings, отрефакторить

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCardHeader/CoinCardHeader.tsx
>          <div
img... 
!!! поправить вёрстку с учётом семантики во всём проекте... 
кнопки - это кнопки, картнки - это картинки... уйти от "дивянки"

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCardHeader/CoinCardHeader.tsx
> +          {coin!.priceChangeFlat >= 0
!!! уйти от использования оператора Non-null assertion "!" во всём проекте... Это хак... Либо в пропсах поменяй тип, чтобы компонента принимала только CoinsData, либо верни null, если coin не пришёл... Ещё лучше сделать это в родителе

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinItemContainer/CoinItem/CoinItem.tsx
> +            +{coin.priceChange?.toFixed(2)}%
зачем optional chaining "?" ?

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinItemContainer/CoinItem/CoinItem.tsx
> +            {coin.priceChange?.toFixed(2)}%
зачем optional chaining "?" ?

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
>            ></div>
Касается всего проекта

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinItemContainer/CoinItemContainer.tsx
> +  const globalStoreContext = useContext(GlobalStoreContext);
const { globalStore } = useContext(GlobalStoreContext);
!!! заюзать деструктуризацию везде, где имеет смысл... тут имеет смысл
касается всего проекта

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinItemContainer/CoinItemContainer.tsx
> +    .sort((a, b) => a.priceChange - b.priceChange);
!!! вся логика в сторах реализуется

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinItemContainer/CoinItemContainer.tsx
> +    />
!!! Отрефакторить... Вот это всё можно сократить в 6 раз !!!  У тебя по сути одни и теже реакт элементы и ты их тупо копипастишь, меняются только данные...

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinItemList/CoinItemList.tsx
>    currency: string;
я бы ограничил category и currency отдельными типами enum, где будут перечислены все возможные значения

2022-09-04 20:26 UTC, nikolya98 commented on src/components/CoinItemList/CoinItemList.tsx
>    let coinListClassNames = "coin__list__container_input_close";
!!! убрать во всём проекте переменные, которые юзаются для хранения стилевых классов, юзай template strings

2022-09-04 20:26 UTC, nikolya98 commented on src/components/Header/Input/Input.tsx
>  import styles from "@components/Header/Input/Input.module.scss";
все ui компоненты обычно складываются где-то отдельно в components...

2022-09-04 20:26 UTC, nikolya98 commented on src/components/Header/Input/Input.tsx
> +  }, [globalStoreContext.globalStore, searchParams]);
это "тупой" ui компонент должен был быть... у тебя слишком много логики здесь... по факту о ндолжен был получать value и setValue через пропсы и всё

2022-09-04 20:26 UTC, nikolya98 commented on src/store/global/GlobalStore.ts
> +}
!!! Много ненужного у тебя в глобальном сторе
1. Для работы с апи нужен отдельный стор с одним общем методом, который бы получал объект с методом и параметрами и тип результата, и юзался бы потом во всех локальных сторах, где есть запросы
2. coins, currency, coinsSearch и всё что ты тут хранишь, я думаю, они не должны быть тут, в глобальном сторе... мне кажется это можно раскидать по соответствующим сторам.... нужно подумать как это лучше сделать.... В глобальном сторе в основном подсторы хранятся.... Переделать структуру сторов!!!

2022-09-04 20:26 UTC, nikolya98 commented on src/store/local/CoinCardApiStore/CoinCardApiStore.ts
> +    });
!!! юзать метод стора запросов

2022-09-04 20:26 UTC, nikolya98 commented on src/store/local/CoinCardApiStore/CoinCardApiStore.ts
> +      };
пожно это делать в статичном методе стора

2022-09-08 20:01 UTC, nikolya98 commented on src/App.module.scss
> +@import "@variables/variables.scss";
этот файл нужен?

2022-09-08 20:01 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.module.scss
> +}
1. стилизуем классами
2. !!! стилизуем по БЭМ: компонентн - блок, всё остальное - элеметы и модификаторы

2022-09-08 20:01 UTC, nikolya98 commented on src/Globals.d.ts
>  declare module "*.module.css";
css есть?

2022-09-08 20:01 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.module.scss
>      height: $app_container_input_close;
camelCase обычно юзается

2022-09-08 20:01 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
> +  const { essencesStore } = useContext(EssencesStoreContext);
!!! нейминг... ты видимо слишком буквально воспинял слово сущность... в твоём проекте сущность это coin, так бы и назвал

2022-09-08 20:01 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
> +      "",
!!! вот это надо было немного по другому сделать... например, можно было вынести куда нибудь в config url апишки и сделать map для endpoint'ов... а не хардкодить это тут... Это вообще в сторе должно быть... у стора метод load например, который всю эту логику скрывает в себе... и тут бы в эффекте этот метод просто вызывался бы...

2022-09-08 20:01 UTC, nikolya98 commented on src/components/CoinCard/CoinCard.tsx
> +                  `coin-price-container__price-change_${
можно было бы лаконичнее назвать)

2022-09-08 20:01 UTC, nikolya98 commented on src/components/CoinItemContainer/CoinItemContainer.tsx
> +    }
.

2022-09-08 20:01 UTC, nikolya98 commented on src/components/CoinItemContainer/CoinItemContainer.tsx
> +      currentCurrency
.

2022-09-08 20:01 UTC, nikolya98 commented on src/components/CoinItemContainer/CoinItemContainer.tsx
> +  const openStoreIsInputSearchOpen = openStore.isInputSearchOpen;
эти константы точно нужны? может можно было бы без них обойтись?

2022-09-08 20:01 UTC, nikolya98 commented on src/components/CoinItemContainer/CoinItemContainer.tsx
> +    currentCoinsSort = coinsFavourites;
!!! эту логику можно было бы в сторе реализовать

2022-09-08 20:01 UTC, nikolya98 commented on src/components/CoinItemList/CoinItemList.tsx
> +        currentCurrency
.

2022-09-08 20:01 UTC, nikolya98 commented on src/components/CoinItemList/CoinItemList.tsx
> +  let openStoreIsInputSearchOpen = openStore.isInputSearchOpen;
можно обойтись без них?

2022-09-08 20:01 UTC, nikolya98 commented on src/components/Header/components/CoinMenu/CoinMenu.tsx
> +  let category = essencesStore.currentCategory;
!!! очень много ненужных переменных создаёшь

2022-09-08 20:01 UTC, nikolya98 commented on src/components/Header/components/CurrencyFilter/CurrencyFilterItem/CurrencyFilterItem.tsx
> +import styles from "@components/Header/components/CurrencyFilter/CurrencyFilterItem/CurrencyFilterItem.module.scss";
зачем тут алиас? Этот файл лежит в той же папке
алиас нужен, если ../../../../ длиннее, чем @components/Header/components/CurrencyFilter/CurrencyFilterItem/CurrencyFilterItem.module.scss, это не тут случай явно

2022-09-08 20:01 UTC, nikolya98 commented on src/components/PageList/PageList.tsx
> +  }, [globalApiStore]);
.

2022-09-08 20:01 UTC, nikolya98 commented on src/store/global/EssencesStore/EssencesStore.ts
> +}
У тебя один огромный стор получился, мог бы сделать 2: один для списка сущностей и ещё один для отдельной сущности...

2022-09-08 20:01 UTC, nikolya98 commented on src/store/global/GlobalApiStore/GlobalApiStore.ts
> +  private _coin: CoinsData | null = null;
!!! этого здесь не должно было быть, в это сторе должен был быть лишь один метод для обращения к апи, который бы юзался в остальных сторах... всё!

2022-09-08 20:01 UTC, nikolya98 commented on src/store/global/GlobalApiStore/GlobalApiStore.ts
> +}
это должно было быть в соответсвующих сторах

2022-09-08 20:01 UTC, nikolya98 commented on src/store/global/GlobalApiStore/GlobalApiStore.ts
> +  };
((

2022-09-09 10:57 UTC, merged

2023-01-07 15:46 UTC, ADdinathe commented on package.json
> +    "mobx": "^6.6.1",
1) Стоит посмотреть еще раз dependencies и devDependencies и убрать все лишее и перенести то что использутеся только при разработке в dev
2)Уд0лить ненужные картинки было бы славно...
3)мне немного не понравилась структура проекта: у тебя лежит index.tsx и все остальное в /components, хотя мне кажется было бы удобнее сделать папку /pages  и положить в нее компонент страницы со списком и со страничкой отдельной монеты
/pages/CoinCard
/pages/CoinsList
общие компоненты вроде кнопок или что-то что используется на обеих страницах оставить в /components
и пр необходимости чтобы слегка облегчить чтение, можно вынести в отдельные компоненты для каждой страницы 
/pages/CoinCard/components
/pages/CoinsList/components

2023-01-07 15:52 UTC, ADdinathe commented on src/store/global/EssencesStore/EssencesStore.ts
> +  }
!!! тут критическая ошибка для логики, ты не должен сортировать то что тебе приходит с бэка, 
потому что если тебе пришло 10 монет и ты их отсортировал и наверху у тебя находится delphi, ты прокрутил вниз и у тебя пришли еще монеты массив стал больше, отсротировался еще раз и наверху у тебя теперь bitcoin, это кринж бро)

при нажатии на категорию сортировки ты должен посылать новый запрос с новым полем order
![image](https://user-images.githubusercontent.com/55657904/211159214-a635a45b-35e8-4fc9-9484-9ba471823d0a.png)

2023-01-07 16:06 UTC, ADdinathe commented on src/store/global/EssencesStore/EssencesStore.ts
> +export default class EssencesStore {
я не очень понял смысла этого стора, потому что ты кидаешь запрос из одного стора, результат кладешь в другой, слишком запутанная логика и плодит много ненужных сторов.
я бы предложил такую структуру:
один стор в котором у тебя логика работы со списком монет, их категориями и валюьами,
там ты хранишь все значения: массив монет, массив валют, метод запроса и обработки монет и валют.

второй стор у тебя отвечаетза работу с query параметрами, его можно оставить как есть

2023-01-07 16:08 UTC, ADdinathe commented on src/store/global/GlobalApiStore/GlobalApiStore.ts
> +  }
все функции-нормалайзеры лучше вынести в отдельные файлы

2023-01-07 16:11 UTC, ADdinathe commented on src/store/global/GlobalApiStore/GlobalApiStore.ts
> +      });
очень длинная функция, ее лучше как-то жекомпозировать и разбить на мелкие методы и вызывать их  в зависимтости от условия

2023-01-07 16:11 UTC, ADdinathe commented on src/store/global/GlobalApiStore/GlobalApiStore.ts
> +    if (requestType === "getCoin") {
все условия типа "getCoin" можно загнать в enum чтобы было проще

2023-01-07 16:15 UTC, ADdinathe commented on src/store/global/GlobalApiStore/GlobalApiStore.ts
> +};
можно так же в types перенести

2023-01-07 16:17 UTC, ADdinathe commented on src/components/PageList/PageList.tsx
> +  }, [essencesStore, globalCurrenciesArray]);
тут можно было бы сделать один объединяющий метод на первый запрос, чтобы не писать 2 эфетка

2023-01-07 16:18 UTC, ADdinathe commented on src/components/PageList/PageList.tsx
> +        ]
если использовать classnames, жизнь станет легче)

2023-01-07 16:19 UTC, ADdinathe commented on src/components/Header/components/CoinMenu/CoinMenu.tsx
> +          }
реально если использовать cn (classnames), то можно будет писать меньше такого кода